#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh gradlew
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «echo», «readonly»,
#           and «test».
#
#   (2) You can optionally export an environment variable JAVA_HOME to
#       specify the JDK location to use for running Gradle. If you don't set
#       JAVA_HOME, the script will try to find a JDK from the OS.
#
#   (3) You can optionally pass a custom JVM options to Gradle using the
#       environment variables JAVA_OPTS or GRADLE_OPTS.
#
#   (4) Use the --no-daemon option to disable the Gradle Daemon. For more
#       information, see:
#
#       https://docs.gradle.org/current/userguide/gradle_daemon.html
#
#   (5) The maximum heap size for the Gradle JVM. You can set it using the
#       environment variable GRADLE_OPTS or JAVA_OPTS. The default is 256m.
#       Example:
#           export GRADLE_OPTS="-Xmx512m"
#
#   (6) The working directory for the Gradle build. You can set it using the
#       environment variable GRADLE_USER_HOME. The default is the user's home
#       directory.
#
#   (7) The Gradle distribution URL. You can set it using the environment
#       variable GRADLE_HOME or GRADLE_USER_HOME. The default is:
#       https://services.gradle.org/distributions/gradle-8.10-bin.zip
#
#   (8) The Gradle wrapper script will download the Gradle distribution from
#       the URL specified in gradle/wrapper/gradle-wrapper.properties if it
#       is not available locally.
#
#   (9) To pass arguments to the Gradle wrapper, use the standard Gradle
#       command-line syntax:
#           ./gradlew [option...] [task...]
#
#   For more details, see:
#
#   https://docs.gradle.org/current/userguide/gradle_wrapper.html
#
##############################################################################

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Set the maximum file descriptors if we can.
if [ "x" != "x" ] ; then
    # macOS
    ulimit -n 1024
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

set -- "$@"

exec "$JAVACMD" "$@"
